### PR TITLE
Thorchain integration2

### PR DESCRIPTION
**Pull request by alexdcox**

### CODE REVIEW

**Comment by alexdcox** [comment]
FYI the only changes to the test data binary files are the 4 byte network id - from bitcoin to dash. The git diff shows different file sizes due to them being compressed with bzip2.

**Review by shotonoff — APPROVED** [review]
LGTM

**Review by shotonoff — COMMENTED** [review]
please check/fix failed tests

**Comment by alexdcox** [comment]
Please can someone merge this now?

**Pull request merged**
